# Generated by Django 5.1.6 on 2025-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login_requires',
            field=models.BooleanField(default=False),
        ),
    ]
